### ISSUE TITLE
firefox: how to pass all test

### ISSUE THREAD

**Issue by erotavlas85** [intoli/intoli-article-materials#13]
Hi,
I read all your posts regarding how to avoid headless detection. I was able to obtain an unique working script with both [first](https://intoli.com/blog/making-chrome-headless-undetectable/) and [second](https://intoli.com/blog/not-possible-to-block-chrome-headless/) set of test by using puppeteer and chromium.
Now after reading how to [inject javascript with selenium and marionette with firefox](https://github.com/intoli/intoli-article-materials/tree/master/articles/javascript-injection), I'm trying to obtain a script that is able to bypass both previous test with firefox.
I already tried both solutions via execute_async_script and via web extension since firefox supports it also in headless mode differently to chromium without success. Quite surely my mistakes are with javascript since I have limited knowledge of it.
Can you point out how to achieve [the same result of chromium with firefox](https://github.com/intoli/intoli-article-materials/tree/master/articles/not-possible-to-block-chrome-headless)? Is there documentation that I can follow?
Thank you
P.S.
I also tried to use an add ons as [greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) or [violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) without success. This should confirm that is something related to javascript.

**Comment by sangaline** [comment]
If you would like your changes to be visible from the page context, then you'll need to break out of the Web Extension's sandbox content script context. Injecting a script tag allows you to run arbitrary code in the page context.

```javascript
const script = document.createElement('script');
script.innerHTML = 'alert("Do something else in here.")`;
document.head.prepend(script)
```

**Comment by erotavlas85** [comment]
I tried with your suggestions and with other solutions, but no one works.
This is a snippet of my python code.
```
try:
    driver.execute_async_script(injectedJavascript) # javascriptFirefox.js file
except:
    print("Timeout")
testUrl="https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html";
driver.get(testUrl)
# other solution
driver.execute_script("const script=document.createElement('script'); script.src='./javascriptFirefox2.js';document.head.appendChild(script);")
driver.get(testUrl)
# your solution
driver.execute_script("const script=document.createElement('script'); script.innerHTML='./javascriptFirefox2.js';document.head.prepend(script);")
driver.get(testUrl)
```
While javascript
javascriptFirefox.js for async
```
var callback = arguments[arguments.length-1];

// overwrite the `languages` property to use a custom getter
const setProperty = () => {
    Object.defineProperty(navigator, "languages", {
        get: function() {
            return ["en-US", "en", "es"];
        }
    });
    
    // Overwrite the `plugins` property to use a custom getter.
    Object.defineProperty(navigator, 'plugins', {
        get: () => [1, 2, 3, 4, 5],
    });
    
    // Pass the Webdriver test
    Object.defineProperty(navigator, 'webdriver', {
      get: () => false,
    });
    callback();
};
setProperty();
```
javascriptFirefox2.js for sync

```
// overwrite the `languages` property to use a custom getter
Object.defineProperty(navigator, 'languages', {
    get: function() {
        return ['en-US', 'en', 'es'];
    }
});

// Overwrite the `plugins` property to use a custom getter.
Object.defineProperty(navigator, 'plugins', {
    get: () => [1, 2, 3, 4, 5],
});

// Pass the Webdriver test
Object.defineProperty(navigator, 'webdriver', {
    get: () => false,
});
```
Maybe the solution is simple, but my limited javascript knowledge does not allow to catch it.
Thank you

**Comment by sangaline** [comment]
If you use `driver.execute_script()` then the code is going to evaluate after the tests have already run. The method of injecting a script tag is specifically for breaking out of the content script context of a Web Extension. You need to put the code that injects the script tag in the content script of an extension, and load that extension using Selenium.

**Comment by erotavlas85** [comment]
I tried also with `driver.execute_async_script()` as I described in the previous message and with extensions as describe [here](https://github.com/intoli/intoli-article-materials/tree/master/articles/javascript-injection).
What is the exact javascript code that I have to use?
Thank you

**Comment by sangaline** [comment]
If you post your extension code here, I'll give you feedback on why it isn't working.

**Comment by erotavlas85** [comment]
I tried with Web extensions as you suggested. I have the test.py, content.js and myscript.js.
File test.py
```
import json
import os
import sys

from selenium import webdriver
from selenium.webdriver.firefox.firefox_profile import AddonFormatError

# Patch in support for WebExtensions in Firefox.
# See: https://intoli.com/blog/firefox-extensions-with-selenium/
class FirefoxProfileWithWebExtensionSupport(webdriver.FirefoxProfile):
    def _addon_details(self, addon_path):
        try:
            return super()._addon_details(addon_path)
        except AddonFormatError:
            try:
                with open(os.path.join(addon_path, 'manifest.json'), 'r') as f:
                    manifest = json.load(f)
                    return {
                        'id': manifest['applications']['gecko']['id'],
                        'version': manifest['version'],
                        'name': manifest['name'],
                        'unpack': False,
                    }
            except (IOError, KeyError) as e:
                raise AddonFormatError(str(e), sys.exc_info()[2])

profile=FirefoxProfileWithWebExtensionSupport()
extension_directory='extension'
profile.add_extension(extension_directory)
firefox_binary='/usr/bin/firefox'
options=webdriver.FirefoxOptions()
# firefox 56+ headless mode https://developer.mozilla.org/en-US/Firefox/Headless_mode
options.set_headless(False)
driver=webdriver.Firefox(options=options, firefox_profile=profile, firefox_binary=firefox_binary)

testUrl="https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html";
driver.get(testUrl)
file="selenium-firefox-extension-script-test.png"
driver.save_screenshot(file)

driver.quit()
```
File content.js
```
const script = document.createElement('script');
script.innerHTML = 'myscript.js';
document.head.prepend(script)
```
File myscript.js
`// overwrite the `languages` property to use a custom getter
Object.defineProperty(navigator, 'languages', {
    get: function() {
        return ['en-US', 'en', 'es'];
    }
});

// Overwrite the `plugins` property to use a custom getter.
Object.defineProperty(navigator, 'plugins', {
    get: () => [1, 2, 3, 4, 5],
});

// Pass the Webdriver test
Object.defineProperty(navigator, 'webdriver', {
    get: () => false,
});`
I do not found any difference between running firefox and firefox developer edition.

**Comment by alfredonodo** [comment]
@erotavlas85 @sangaline I can confirm that it does not work for me too.

**Comment by sangaline** [comment]
Ah sorry, I forgot to remove the comments. What about this for the content script?

```javascript
const script = document.createElement('script');
script.innerHTML = `
Object.defineProperty(navigator, 'languages', {
    get: function() {
        return ['en-US', 'en', 'es'];
    }
});

Object.defineProperty(navigator, 'plugins', {
    get: () => [1, 2, 3, 4, 5],
});

Object.defineProperty(navigator, 'webdriver', {
    get: () => false,
});
`;
document.head.prepend(script)
```

Also note that you'll want to set `"run_at": "document_start"` for the content script in the extension manifest.

**Comment by erotavlas85** [comment]
No, it does not work. `"run_at": "document_start"` yes.

**Comment by sangaline** [comment]
Is the script tag actually being injected? Are there console errors in the developer tools?

**Comment by erotavlas85** [comment]
Analysing the source code there is not injected code.
The console error: `TypeError: document.head is null content.js:17:1` the error is on `document.head.prepend(script)`

**Comment by sangaline** [comment]
Hmmm, I would expect that to be defined at `document_start`. Sorry, I don't have an answer off the top of my head on this. I'll reopen this issue though, and we'll put out an article in the near future that includes working code for this. Please do comment here if you figure it out in the meantime though, there are a couple of people following this thread.

**Comment by erotavlas85** [comment]
I found the reason for which `document.head is null`. According to [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts) of content_script, with the attribute run_at=document_start, is load after html tag and so before the head tag. A similar behaviour [here](https://stackoverflow.com/questions/28186349/chrome-extension-set-to-run-at-document-start-is-running-too-fast).
I found a solution:
File content.js
```
var script=document.createElement("script");
script.src=browser.extension.getURL("myscript.js");
script.async=false;
document.documentElement.appendChild(script);
```
It works like a charm :)

**Comment by erotavlas85** [comment]
@sangaline I noticed that if I use the standard profile, the Web Extensions script solution works well both with firefox and firefox developer edition. Whereas if I use a custom profile with add ons on custom settings, I have to use firefox developer edition.
Is it an expected behaviour?

Standard profile
```
class FirefoxProfileWithWebExtensionSupport(webdriver.FirefoxProfile):
    def _addon_details(self, addon_path):
        try:
            return super()._addon_details(addon_path)
        except AddonFormatError:
            try:
                with open(os.path.join(addon_path, 'manifest.json'), 'r') as f:
                    manifest = json.load(f)
                    return {
                        'id': manifest['applications']['gecko']['id'],
                        'version': manifest['version'],
                        'name': manifest['name'],
                        'unpack': False,
                    }
            except (IOError, KeyError) as e:
                raise AddonFormatError(str(e), sys.exc_info()[2])

profile=FirefoxProfileWithWebExtensionSupport()
extension_directory='extension'
profile.add_extension(extension_directory)
```
Custom profile
```
class FirefoxProfileWithWebExtensionSupport(webdriver.FirefoxProfile):
    def _addon_details(self, addon_path):
        try:
            return super()._addon_details(addon_path)
        except AddonFormatError:
            try:
                with open(os.path.join(addon_path, 'manifest.json'), 'r') as f:
                    manifest = json.load(f)
                    return {
                        'id': manifest['applications']['gecko']['id'],
                        'version': manifest['version'],
                        'name': manifest['name'],
                        'unpack': False,
                    }
            except (IOError, KeyError) as e:
                raise AddonFormatError(str(e), sys.exc_info()[2])

profile_folder="profile_path"
profile=FirefoxProfileWithWebExtensionSupport(profile_folder)
```
extension_directory='extension'
profile.add_extension(extension_directory)

**Comment by alfredonodo** [comment]
@sangaline @erotavlas85 
I noticed that the WebGL Vendor and Renderer [test](https://intoli.com/blog/making-chrome-headless-undetectable/) only works without headless mode, while with headless the fields are empty.
Do you know how to bypass it? I also read about this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1375585).
